name: "Continuous Integration"

env:
  PYTHON_VERSION: '3.12'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
    
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          pip install coverage
      
      - name: Lint with pylint
        run: |
          pylint src/

      - name: Test with coverage
        run: |
          python -m coverage run --source src -m unittest discover -s tests
          python -m coverage report -m
